spring.application.name=SchoolManagementR2dbc
spring.data.r2dbc.repositories.enabled=true
spring.r2dbc.url=r2dbc:mssql://localhost:1433/reactnonreact
spring.r2dbc.password=reactnonreact
spring.r2dbc.username=reactnonreact
logging.level.io.r2dbc.mssql=debug
